---
# https://docs.gitlab.com/ee/ci/docker/using_docker_build.html

stages:
  - commit
  - syntax
  - test-centos
  - test-debian
  - test-ubuntu
  - module

# commit
git-history:
  stage: commit
  script:
    - >
      bash <(curl --fail --location --silent --show-error
      https://git.io/vxIxF)

lines-length:
  stage: commit
  script:
    - >
      bash <(curl --fail --location --silent --show-error
      https://git.io/vxIxN)
      80 templates/* files/*

# syntax
erb-lint:
  stage: syntax
  image: vpgrp/linter:puppet
  script:
    - rails-erb-lint check --path=templates

json-lint:
  stage: syntax
  image: vpgrp/linter:puppet
  script:
    - metadata-json-lint metadata.json

markdown-lint:
  stage: syntax
  image: vpgrp/linter:markdown
  script:
    - markdown-lint README.md

puppet-lint:
  stage: syntax
  image: vpgrp/linter:puppet
  script:
    - puppet-lint --fail-on-warnings .

rubocop:
  stage: syntax
  image: vpgrp/linter:ruby
  script:
    - rubocop .

yaml-lint:
  stage: syntax
  image: vpgrp/linter:yaml
  script:
    - yaml-lint .gitlab-ci.yml
    - yaml-lint .kitchen.yml
    - yaml-lint .puppetforge.yml

# puppet
centos-6:
  stage: test-centos
  image: vpgrp/kitchen
  script:
    - kitchen test --destroy=always --color centos-centos-6

centos-7:
  stage: test-centos
  image: vpgrp/kitchen
  script:
    - kitchen test --destroy=always --color centos-centos-7

debian-8:
  stage: test-debian
  image: vpgrp/kitchen
  script:
    - kitchen test --destroy=always --color debian-debian-8

debian-9:
  stage: test-debian
  image: vpgrp/kitchen
  script:
    - kitchen test --destroy=always --color debian-debian-9

debian-10:
  stage: test-debian
  image: vpgrp/kitchen
  script:
    - kitchen test --destroy=always --color debian-debian-10

ubuntu-14.04:
  stage: test-ubuntu
  image: vpgrp/kitchen
  script:
    - kitchen test --destroy=always --color ubuntu-ubuntu-14-04

ubuntu-16.04:
  stage: test-ubuntu
  image: vpgrp/kitchen
  script:
    - kitchen test --destroy=always --color ubuntu-ubuntu-16-04

# create module
create-module:
  stage: module
  image: vpgrp/puppet
  script:
    - puppet module build

publish-module:
  stage: module
  only:
    - master
  image: vpgrp/puppet
  script:
    - rake module:push
# EOF
